### ISSUE TITLE
MHF feature list

### ISSUE THREAD

**Issue by Andoryuuta** [ErupeServer/Erupe#3]
It would be nice if we had high level list of features/systems available in MHF to compare our implementation progress to.

**Comment by SirFist** [comment]
The packet capturing checklist should cover (nearly) all aspects of the game but obviously doesn't account for what we find is client side, could be adapted for this fairly easily.
https://docs.google.com/spreadsheets/d/1eUQp8SmK31Z44ZmrseJvs49pVObQBij28z19wMRV7_4/edit
