### ISSUE TITLE
Implement ラヴィエンテ/Laviente/Raviente

### ISSUE THREAD

**Issue by Andoryuuta** [ErupeServer/Erupe#36]
Implement base code for starting server-wide ravi event, queuing players, and entering stage.

Unclear if ravi movement is completely owned by the server, or if it's p2p/owned by the initiator like normal quests.

**Comment by Guanzorm** [comment]
If the host player disconnect because of network fluctuations, he will find that the other players stop moving. If Laviente still moving at this point, it says that Laviente movement is controlled by the host player.
So we need to find some game live playback to confirm it.
