### ISSUE TITLE
got save issue

### ISSUE THREAD

**Issue by Solenataris** [ErupeServer/Erupe#39]
sup

i had this error message :  

2020-12-16T20:36:04.558+0100    INFO    main.channel.127.0.0.1:50670    channelserver/handlers.go:1094  Wrote recompressed savedata back to DB.
2020-12-16T20:36:04.559+0100    FATAL   main.channel.127.0.0.1:50670    channelserver/handlers.go:1138  Error dumping savedata  {"error": "open savedata\\1608147364.bin: access denied"}
github.com/Andoryuuta/Erupe/server/channelserver.dumpSaveData
        C:/Program Files (x86)/CAPCOM/Monster Hunter Frontier Online/Erupe/server/channelserver/handlers.go:1138
github.com/Andoryuuta/Erupe/server/channelserver.handleMsgMhfSavedata
        C:/Program Files (x86)/CAPCOM/Monster Hunter Frontier Online/Erupe/server/channelserver/handlers.go:1096
github.com/Andoryuuta/Erupe/server/channelserver.(*Session).handlePacketGroup
        C:/Program Files (x86)/CAPCOM/Monster Hunter Frontier Online/Erupe/server/channelserver/session.go:189
github.com/Andoryuuta/Erupe/server/channelserver.(*Session).handlePacketGroup
        C:/Program Files (x86)/CAPCOM/Monster Hunter Frontier Online/Erupe/server/channelserver/session.go:194
github.com/Andoryuuta/Erupe/server/channelserver.(*Session).handlePacketGroup
        C:/Program Files (x86)/CAPCOM/Monster Hunter Frontier Online/Erupe/server/channelserver/session.go:194
github.com/Andoryuuta/Erupe/server/channelserver.(*Session).handlePacketGroup
        C:/Program Files (x86)/CAPCOM/Monster Hunter Frontier Online/Erupe/server/channelserver/session.go:194
github.com/Andoryuuta/Erupe/server/channelserver.(*Session).handlePacketGroup
        C:/Program Files (x86)/CAPCOM/Monster Hunter Frontier Online/Erupe/server/channelserver/session.go:194
github.com/Andoryuuta/Erupe/server/channelserver.(*Session).recvLoop
        C:/Program Files (x86)/CAPCOM/Monster Hunter Frontier Online/Erupe/server/channelserver/session.go:149
github.com/Andoryuuta/Erupe/server/channelserver.(*Session).Start.func1
        C:/Program Files (x86)/CAPCOM/Monster Hunter Frontier Online/Erupe/server/channelserver/session.go:66
exit status 1

it's a problem of save data ? however my folder is created.

**Comment by Andoryuuta** [comment]
Oh, curious. I thought I fixed this already.

Is this on the latest commit/version of Erupe from this Github repo?

**Comment by Solenataris** [comment]
yes.
Latest version.
Downloaded a few days ago.

**Comment by Solenataris** [comment]
up

problem fixed by running erupe as a administrator.

dunno why without that, the save folder has access denied.

also, i edited the file handlers.go to make erupe functional.
