### ISSUE TITLE
ReSkin GameLauncher

### ISSUE THREAD

**Issue by R5GAMER** [ErupeServer/Erupe#42]
I know this is not an essential element, but I decided to reskinned the GameLauncher, so that it is closer to the original one, the js css functions are directly installed in the server which will allow it full autonomy, the js codes have been little adjusted to make it respond a little more faster, but I think the slowness comes from the launcher directly. I do not know however if I add the sounds of effects identical to the launcher or not,
The error management is displayed in the black box above configuration, this window will display the connection status.
The save account box is non-functional at this time, but it will be shortly after I have concluded the next part.
I'm working on the character selection right now.  I will make updates to this post. (Sorry for my bad english)

![Work1](https://user-images.githubusercontent.com/9487937/108416040-1f09ed00-7226-11eb-8c85-e2e33e52ed41.jpg)

R5GAMER.

**Comment by Solenataris** [comment]
hi, 

this is really a nice work, and i'am interessed by your custom launcher.

i planned to remake the base client but i'm not good at coding.. lel

but, i noticed some things 

1. i think it's more private server (not server private) and even, it's not a very interesting thing to show.
2. it's possible to edit background or even add randoms background who can change everytime you start the client ?
3. do you think there is a way to upgrade logo quality ?

i'm curious about your project, hope you will release that soon. ^^

**Comment by R5GAMER** [comment]
From what I understand I think the author of this git account worked on a new client to make mhfo.dll and mhfo-hd.dll work, and how they handle it, I can possibly to coded it (on c#) but I don't understand how they work with these dlls.

For the three points:
- It's sad to make it too private, because by testing it the server works perfectly, of course there are crashes and the quest files are missing but for me it's entirely enough to try to learn and help, I was really happy to be able to launch it again.
- I can add this function, if people have other interesting ideas I can try to work on it.
- The logo can be replaced, but I will recommend to respect the size, like the background image or for the button.
In any case, the whole weighs 4 mb (the heaviest files are the js files) I was able to launch the game during my trip on the plane without having to connect to the internet.

R5GAMER

**Comment by Solenataris** [comment]
yes, i saw that too. I think the best thing to do is to ask to ando directly.

maybe his client is just a upgrade of what is currently existing and not a visual thing.

I don't think it's totally private, because some quest files are released on archive.org, it's gathering quest, gr1 pokaradon and Raviente.

I'm interessed to help with that, even if my skills in coding are terrible.

I created my own logo of mhfz, i can reduce the size i think, i already did some test and i have something but not very nice in comparison on what you did.

**Comment by R5GAMER** [comment]
I succeeded in obtaining the logo of the game by extracting the resources, I will be able to replace the logo, in fact I took the logo at random xD, if you have the images to put it in the background it is with pleasure ! I added sound in launcher.

**Comment by Solenataris** [comment]
i though about official artwork of mhf as shantien, zenith rathalos, harudo etc... but i want to know something because i'm curious.
how did you do to extract launcher data ? because i searched but i didn't found anything :/
i'll be happy to help. :)

**Comment by R5GAMER** [comment]
i used : https://github.com/mhvuze/ReFrontier 
You open up project and build it (with Visual Studio Community), after this you can use a tools, drag and drop a file into .exe (in ReFrontie/bin/Debug/ReFrontier.exe) & (all file contains textures of all menu is in /folder game/dat/ see screenshoot)

![titre](https://user-images.githubusercontent.com/9487937/108591643-b031ae80-7361-11eb-9fc6-f242149b7aa8.png)

**Comment by Solenataris** [comment]
all in one ?
yeah i have refrontier and i already use it for modding

**Comment by R5GAMER** [comment]
If you select are files it didn't work, you need to put one by one.

**Comment by Solenataris** [comment]
.bin too ?

**Comment by R5GAMER** [comment]
.bin too

**Comment by Solenataris** [comment]
launcher data (html css etc...) are in all files ?

**Comment by R5GAMER** [comment]
There not ressources launcher is just ressources games

**Comment by Solenataris** [comment]
do you have a idea of when you can release files ? i'm pretty interessed.

**Comment by R5GAMER** [comment]
I work on it in my spare time, and I want to get it right enough so I won't be able to tell you too much when but it won't take forever either. I upload a git, on my account if the author of this git is not interested.

**Comment by Solenataris** [comment]
kek, just tell me when it's done.

**Comment by Solenataris** [comment]
up.
for random artworks, what is the resolution of the client window ? I'll give you if i have the time, some edited files with the good resolution.

**Comment by Andoryuuta** [comment]
Hi @R5GAMER!

Interesting reskin, it looks very neat!

Unfortunately, this would not be a good fit for this repository. For legal reasons, I am keeping the repo entirely clear of any copyrighted content from the game and it's developers. This includes any of the company logos, game images, or otherwise.

I will also note that the original launcher HTML/js/css is supported by the emulator, if you have a backup of them from when the original servers were online. Again, none of these files can be redistributed for legal reasons. This is why the server emulator ships with a very plain and basic HTML launcher currently.

Thanks for reaching out with this possible contribution, and I hope you understand why it cannot be placed into this repository.

Thanks,
Andoryuuta

**Comment by R5GAMER** [comment]
Offer me a precise repository and I can then do it because it is all even work lost. We could keep the same except that we only change the logos and image.

**Comment by Solenataris** [comment]
Sending it in github is not mandatory, you can perfectly upload it elsewhere.
Drive, mediafire, or even archive.org

**Comment by R5GAMER** [comment]
In this case, I will put it directly in my github. Seen, that we close directly without finding an alternative solution. Even if I understand his point of view.

**Comment by Solenataris** [comment]
Yhea i think it's better.

(btw it's possible to contact by another way than git ?it's still about launcher and mhf)

**Comment by R5GAMER** [comment]
Do you have a discord ?

**Comment by Solenataris** [comment]
Yes.
It's Ygnaris#8304
