### ISSUE TITLE
NOTICE: Project status and legal information

### ISSUE THREAD

**Issue by Andoryuuta** [ErupeServer/Erupe#45]
As there have been a large amount of issues about the status of this project, known issues, **and those discussing the distribution of copyrighted material**, I thought it best to create a single issue to direct people to with the information they need.

## Project Status: **Not Usable for Play**
There are many large issues which are known, however they will take large effort to resolve (#43, #44, etc), as well as many LARGE portions of the codebase that needs to be refactored, and MANY packet handlers and shared packet formats (e.g. Communicator-classed packets) that need to be reverse engineered and implemented. As the prequisites to work are this project are copyrighted, they cannot be shared even with those who wish to "help work on the project".

## Legal Information
This repository is being kept entirely clear of any copyrighted material from the game, and it's developers. This includes, but is not limited to, game client binaries, game images, music, storybooks, **quest binaries**, etc.

**DO NOT** discuss the the distribution of copyrighted materials on this issue tracker / repository. Any issues linking to copyrighted material will be deleted

**DO NOT** send pull requests containing copyrighted material. Any of these will also be rejected.

**Comment by Solenataris** [comment]
I know it's out of context but, do you have a small list of not implemented features ? Or it's something who needs to stay on private side.

**Comment by Andoryuuta** [comment]
Non implemented features would include Mezfes, proper different channels/world, farm/garden, hunter road, ravi, bars, a proper implementation of stages, real authentication, and much much much more.
