### ISSUE TITLE
game fails to launch

### ISSUE THREAD

**Issue by suzaku830** [ErupeServer/Erupe#48]
I follwed your instruction and set up server, then started the game with py file that bypass GameGuard protection.
After creating an account and selecting a character, I got the error "Monster Hunter Frontier Z could not be started. The file could not be read."
It didn't start even if I disabled McAfee or lowered the image quality setting.
Here is a screenshot.
https://imgur.com/a/qGGHWnb
Is there any solutions?
Any help would be greatly appreciated.
Thank you.

**Comment by Solenataris** [comment]
re install direct x or disable high grade.

**Comment by suzaku830** [comment]
I noticed that the installed files do not contain files such as mhfo.dll so I got another installer, and then works fine with disabling high grade.
My next target is quest, but thank you for your advice.

**Comment by imkedux** [comment]
i have the exact same problem but it wasnt fix by doing that any other ideas of how to fix it?
