### ISSUE TITLE
game guard not opening the game and giving error

### ISSUE THREAD

**Issue by soulmizute** [ErupeServer/Erupe#49]
this is probably just something really stupid but i wanted to test the game for any potential game breaking glitches but the game wouldnt let me in and i dont know why

**Comment by ricochhet** [comment]
I'm sure you'll find the information you need here: [https://github.com/ErupeServer/Erupe/issues/40](https://github.com/ErupeServer/Erupe/issues/40).

Do note that if you plan to "test the game for any potential game breaking glitches," you will find them. If you find something notable, properly documenting the issue, attempting to decipher where the issue arose, and providing steps to reproduce the issue would be ideal.

I know this is a late response, and I hope you would've figured it this out by now, but if you didn't I sincerely doubt your goal is to "test." Testing a game would require advanced knowledge about computers, and troubleshooting. I would place good bets that one of, if not your main goal is to simply play the game...and, you should feel free to, but do note this is not a complete experience and is very barebones, things are going to break, implode, and shatter the multiverse.
