### ISSUE TITLE
Trying to find out why the login part of the launcher says "error logging in!"

### ISSUE THREAD

**Issue by Diablonemes** [ErupeServer/Erupe#51]
I'm just needing to know as i did everything correctly I hope, if any one knows why this is happening please tell me.

**Comment by ricochhet** [comment]
We'd need a bit more to go off of other than "I have an error." I would assume a message of some sort would appear in the server console log. Could you please either copy-paste it, or send a screenshot. It might be able to help determine what the actual issue is. The launcher messages aren't very descriptive.

**Comment by Diablonemes** [comment]
sorry am still a bit new-ish to this stuff, but i don't see any message in the server console log that says anything with the error, the launcher also doesn't say the error until a bit later. all that i would see in the console log is this:
127.0.0.1 - - [09/Aug/2021:01:23:14 -0500] "GET /serverlist.xml HTTP/1.0" 200 113

**Comment by ricochhet** [comment]
Hmm, first I would check that the postgres database is up and you ran the necessary migrate command, make sure your hosts file has the necessary domains. 

I would also make sure to verify that everything in the Erupe config is correct.

After you've verified everything should be operational there's one addition "quirk" with the launcher you could be experiencing.

Occasionally when attempting to input login credentials the input boxes may not function properly and require multiple clicks to select it, or it simply doesn't register.

A way to get around this is at the login screen is simply double click each thing you want to select. This issue isn't present on any other part of the launcher.

I know in the past I've experienced a similar issue to you, where everything was running fine, but the launcher would still spit out an error, strangely enough that double clicking trick seemed to have worked in my instance. 

If that doesn't work and you verified everything is seems correctly done, let me know, and we can go from there. :)

**Comment by Diablonemes** [comment]
i don't know if it's me or that when trying to put in the migrate command it doesn't do anything. i installed what i needed but i don't know why it's not doing anything. think that is the problem.

**Comment by ricochhet** [comment]
First make sure migrate is installed correctly, via `migrate --version`. If nothing appears it's likely not installed correctly, make sure you installed it via scoop. If for some reason scoop doesn't install it, you can download it from `https://github.com/golang-migrate/migrate/releases/tag/v4.14.1`, and add it to your environment variables. 

If it is installed, make sure the database is actually running, if it is you should make sure you're executing the command in the correct location. The command should be ran in the same directory as the Erupe server files.

**Comment by Diablonemes** [comment]
i checked if i had it installed and it was, but still no matter what nothin pops up when i put the correct command in the same directory of erupe server files. i don't know what else is going on if it doesn't work. this is what i get:
`D:\Erupe-master>migrate -database postgres://postgres:Redy5566@localhost:5432/erupe?sslmode=disable -path migrations up
no change
`

**Comment by ricochhet** [comment]
It seems like migrate isn't the issue, assuming you accidently misformatted, you used the command, `D:\Erupe-master>migrate -database postgres://postgres:Redy5566@localhost:5432/erupe?sslmode=disable -path migrations up`, and it gave an output of `no change`, which likely indicates that it worked.

If you seem sure you did everything correctly, I would check your firewall settings, or anti-virus settings. If those don't seem to interfering, you could always attempt to start over, or if you want, explain the process you used step-by-step. Is there anything else you may suspect be the cause? Like I mentioned previously, check everything else I mentioned [here](https://github.com/ErupeServer/Erupe/issues/51#issuecomment-895218353) too.

**Comment by Diablonemes** [comment]
mind telling me what you mean by "start over"? Pretty sure i did everything correctly, and no i don't suspect anything causing this issue. For the firewall or antivirus, is there a certain setting i would see if it was causing the issue?

**Comment by K-Lemu** [comment]
Which IP address did you enter in the "host_ip" and "ip" sections in config.json?

I was in the same situation, and when I checked various things.
If you enter the external IP in config.json and the entry for localhost (127.0.0.1) in hosts, the same phenomenon will occur if the router doesn't support [nat-loopback].
Of course, I have set up port forwarding, but it is very strange that it may not be possible depending on the router.

**Comment by Diablonemes** [comment]
i tried putting the external ip of mine in host ip, and the rest as localhost. what i saw.

**Comment by K-Lemu** [comment]
Enter localhost (127.0.0.1) for both "host_ip" and "ip", and enter localhost for hosts as well, and try it.
(I have never tried with separate IPs.)
Also, try deleting the IE cache once after inputting and before starting the server.

I don't know if the linksys router supports [nat-loopback], and I don't know if the cause is [nat-loopback]. 
(In my environment, if I enter an external IP, it only succeeds on a router that supports nat-loopback.)

However, if you want to enter an external IP for both "host_ip" and "ip", I think that port forwarding settings are essential.

**Comment by Diablonemes** [comment]
it's working now, thank you. though if i was to do quests i need scenerio files i think?

**Comment by K-Lemu** [comment]
I don't know what the scenario file means and which quest it affects.
However, the quest itself is possible even if there is no scenario, and I think that the reason why it keeps loading forever is that the quest file you are trying to do is not placed in bin.
Questions about quest files etc. are not appropriate here so please look them up yourself.
