### ISSUE TITLE
'go run .' returns fatal error.

### ISSUE THREAD

**Issue by negitausen** [ErupeServer/Erupe#52]
Hi! Whenever I use the 'go run .' command, cmd returns the following error:

`D:\Other Games\Monster Hunter Frontier\Erupe-aac4e77d49f0060ed857a304df0575271ebf3c84>go run .
2021-09-14T02:59:48.942+0200    INFO    main    Erupe-aac4e77d49f0060ed857a304df0575271ebf3c84/main.go:34       Starting Erupe
2021-09-14T02:59:51.025+0200    FATAL   main    Erupe-aac4e77d49f0060ed857a304df0575271ebf3c84/main.go:60       Failed to ping database {"error": "dial tcp 92.176.196.208:5432: connectex: No connection could be made because the target machine actively refused it."}
main.main
        D:/Other Games/Monster Hunter Frontier/Erupe-aac4e77d49f0060ed857a304df0575271ebf3c84/main.go:60
runtime.main
        C:/Program Files/Go/src/runtime/proc.go:255
exit status 1`

Every prior step worked correctly. I think it may be a port forwarding issue, but I have done it correctly (I think, since I'm not really well versed in this) and have edited the fields in the command.json file multiple times (especially to try combinations since whatsmyip and my router give out different results. Even then, I've tried every possible setting and none worked).

What does this error message mean and how can I avoid it on my side? Thanks in advance and sorry if this doesn't belong here.

**Comment by Falld0wn18** [comment]
`Failed to ping database {"error": "dial tcp 92.178.198.206:5432: connectex: No connection could be made because the target machine actively refused it."}`

Make sure you can access your database :)

**Comment by Andoryuuta** [comment]
You _really_ don't want to have your PostgreSQL port-forwarded and exposed on the public internet like that. Instead, install PostgreSQL on the same server with the Erupe server, and use `127.0.0.1`/localhost fort the database config.
