### ISSUE TITLE
Error when selecting initial character in launcher

### ISSUE THREAD

**Issue by ChristianSantamaria** [ErupeServer/Erupe#53]
I have been following all the steps but when selecting the initial character I get this error, I do not know if it opens something wrong but I have repeated the installation a couple of times and the error prevails. I need help
Thanks 
![image](https://user-images.githubusercontent.com/22427989/137031429-e31bf20b-8de8-4181-bc88-4c416f20f8f4.png)
![image](https://user-images.githubusercontent.com/22427989/137031857-a543c24c-1785-4c18-922e-d337ae30f76c.png)

**Comment by Kraballa** [comment]
I have encountered this same issue. I've also spent some time asking around and the responses I got boiled down to that it just doesn't work. All we can do is wait and see what happens for now.

**Comment by jet082** [comment]
No one can understand an error that is just "???????????" Run it through a local emulator.

However, I almost assure you that the issue is that you have not patched the anti-cheat measures out of the dll/exe. Do that and you should be good.

**Comment by Maknollram** [comment]
On some tests I made, this error happen when I installed the MHF, via the game installer, after unninstall via the installer, I dont get this error
