### ISSUE TITLE
py no_gg_jp.py failing to do anything due to a dll file not importing frida

### ISSUE THREAD

**Issue by soulmizute** [ErupeServer/Erupe#54]
firstly please understand that iam not a code person. secondly please know that everything up to this point has worked and i can open pg4 admin with the database and the go run command works in connecting to the database,
i have a feeling i did something wrong with the frida download process but im not sure
heres what i get when i try to run the launcher:
Failed to load the Frida native extension: DLL load failed while importing _frida: The specified module could not be found.
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "C:\Users\IonisedOnion\OneDrive\Desktop\Monster Hunter (Japan)[SLPM-65495]-English-Patched\monster hunter frontier\a51d9f79114d64946b9e0656cdc0a72e-f36890d8929f929da0c103d705dcba4454f803f8\no_gg_jp.py", line 12, in <module>
    import frida

please may someone correct my mistakes as im very confused, thank you
edit: thought i'd also mention i didn't do the port forwarding as i dont trust myself to do it
fixed the origional problem but now i need a frida module so how do i get that and where do i put it

**Comment by Kugahara** [comment]
In my case some Python version works correctly but some doesn't, now I'm using 3.9.1(amd64).
And for Frida I aslo had problem, that typing "pip install frida" manually in command prompt got error while installing, so I go https://pypi.org/project/frida/ and get the installation code then copy and paste.

Furthermore I Installed go lang 1.16.9 becasue latest one has an error and I'm not sure how to fix it.
Hope this help you.

**Comment by soulmizute** [comment]
so i need to re download python and maybe golang. thats fine

**Comment by soulmizute** [comment]
im now also having this problem
 File "c:\users\ionisedonion\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ionisedonion\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\IonisedOnion\AppData\Local\Programs\Python\Python39\Scripts\pip.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'pip'

**Comment by mehrdavon** [comment]
Try "pip --version".
If it doesn't work, check if your PATH configuration is correct.
If you've just installed Python, a reboot is highly recommended.

Suggestion: Instead of asking here, please try googling the issues you are facing as these are not Erupe related.
